version: "3.8"
name: express-starter
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass redis"
    ports:
      - 6379:6379
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672" # UI
  express:
    container_name: express
    stdin_open: true
    env_file:
      - .env.local
    build:
      context: ./app/ # path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app # sync files between host and container to enable hot-reloading
      - /app/node_modules # do not share node_modules from host to container. Basically, you are specifying the directories that shouldn't be reloaded in the container
  worker:
    container_name: worker
    stdin_open: true
    build:
      context: ./worker
    depends_on:
      - express
    volumes:
      - ./worker:/worker
      - /worker/node_modules

volumes:
  postgres-data:
